### ISSUE TITLE
Can't login to my homeserver in Element web app (HTTP 302)

### ISSUE THREAD

**Issue by CodeShakingSheep** [YunoHost-Apps/element_ynh#134]
### Describe the bug

When I click on "Continue with CAS" button, the request returns a `HTTP 302 Not Found` response (see screenshot). 

![image](https://github.com/YunoHost-Apps/element_ynh/assets/19874562/ab8fc094-ac5b-4c41-a57b-7c955ed4157e)

Afterwards I'm being redirected to the YNH portal. Element Desktop app and Element mobile app work flawlessly. So, I don't assume that there is an issue with my synapse installation. It's really just that I cannot login to the web app.

### Context

- Hardware: VPS bought online
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Steps to reproduce

1. Click on "Sign In"
2. Enter your synapse home server domain
3. Click on "Continue with CAS" button

### Expected behavior

I should be taken to the login form of my home server and be able to successfully login.

### Logs

I don't have any useful logs about this.

**Comment by Josue-T** [comment]
Closing as duplicate https://github.com/YunoHost-Apps/element_ynh/issues/122 https://github.com/YunoHost-Apps/synapse_ynh/issues/412
