### ISSUE TITLE
session and login persistance

### ISSUE THREAD

**Issue by LiohMoeller** [YunoHost-Apps/element_ynh#17]
I have set up riot as a private application on yunohost. If I access the app using the yunohost portal, everything works as expected. If I try to access the application through the deeplink I have to login again, even though I have an active session open on yunohost and am authenticated there.
The negative side effect is that on every new login a new encryption key is generated.

**Comment by Josue-T** [comment]
> If I try to access the application through the deeplink I have to login again, even though I have an active session open on yunohost and am authenticated there.

Hello, well, what do you mean by the "deeplink" ?

Maybe can you explain exactly how to reproduce the bug ?

**Comment by Josue-T** [comment]
Closing, please reopen if you still have the issue.
