### ISSUE TITLE
Make sure versions support Firefox ESR

### ISSUE THREAD

**Issue by olberger** [YunoHost-Apps/element_ynh#172]
It seems that the release process of Element on app.element.io suffered from an uncontrolled bump of some API, which render it unusable with Firefox ESR (see https://github.com/element-hq/element-web/issues/27682)

Therefore, it would be great to avoid packaging, for YNH, a version that isn't compatible, until https://github.com/element-hq/element-web/issues/27684 is resolved.

Hope this helps,

**Comment by olberger** [comment]
Well, it seems that the version installed by the app is indeed displaying the infamous bug in question https://github.com/element-hq/element-web/issues/27682

I'd advise for reverting to the previous version, then

**Comment by olberger** [comment]
AFIU, it installed from https://github.com/element-hq/element-web/releases/download/v1.11.70/element-v1.11.70.tar.gz so I guess the previous version would be better suited ([v1.11.69](https://github.com/element-hq/element-web/releases/tag/v1.11.69))

**Comment by isAAAc** [comment]
@olberger : 

> keep in mind you can't roll back from 1.11.70 because the Rust Crypto database format changed and it is irreversible.

in: https://github.com/element-hq/element-web/issues/27684

**Comment by isAAAc** [comment]
new esr version today in debian : 
```
# dpkg -l |grep firefox
ii  firefox-esr                              115.13.0esr-1~deb12u1                          amd64        Mozilla Firefox web browser - Extended Support Release (ESR)
ii  firefox-esr-l10n-en-gb                   115.13.0esr-1~deb12u1                          all          English (United Kingdom) language package for Firefox ESR
```

**Comment by isAAAc** [comment]
to install ffox esr 128.0 on debian:
https://support.mozilla.org/en-US/kb/install-firefox-linux#w_install-firefox-deb-package-for-debian-based-distributions (and use firefox-esr instead of firefox when `apt install`
