### ISSUE TITLE
Can't use the app

### ISSUE THREAD

**Issue by stemy2** [YunoHost-Apps/element_ynh#18]
Hello,

I can't load the app, i have nothing but a spinning wheel and nothing else happens, no matter how long i'm waiting.

**Comment by Josue-T** [comment]
Hello,

Which browser do you use ? And have you tried with an other browser ?

**Comment by stemy2** [comment]
Abrowser. I tried with icecat and it works.

**Comment by Josue-T** [comment]
Maybe could be a plugin which block something in riot

**Comment by stemy2** [comment]
This is really strange, my own domain is whitelisted for every addon.

**Comment by Josue-T** [comment]
Ok but you could have some dependance of the matrix ecosystem.

**Comment by stemy2** [comment]
I have a local install of synapse, nothing is sent outside the server.

**Comment by Josue-T** [comment]
Closing this, please reopen if you still have the issue.
