### ISSUE TITLE
Installation fails when the default_home_server is not in the list of domains, but a subdomain is

### ISSUE THREAD

**Issue by eauchat** [YunoHost-Apps/element_ynh#19]
When I was installing riot_ynh, the installation was failing.
I noticed that in the log there was the following:
```
++ yunohost domain list
++ grep chosenMatrixDomain.tld
+ [[ -n   - something.chosenMatrixDomain.tld
  - sub.chosenMatrixDomain.tld
  - other.chosenMatrixDomain.tld ]]
++ readlink -f /etc/yunohost/certs/chosenMatrixDomain.tld/crt.pem
+ cert_path=
+ ynh_exit_properly
```
In this `chosenMatrixDomain.tld` is the default matrix instance I want users to be proposed to connect to (`default_home_server`).
From those logs I figured there was a problem with the fact that `chosenMatrixDomain.tld` was not added to the list of domains in my yunohost. So I added it, then I could install riot fine. And then I removed it and everything seem to work fine.

I wonder what this step of looking for the certificate of the domain is used for. `chosenMatrixDomain.tld` is not the domain where riot is installed, but the one where synapse is served, so I don't understand why riot would need to search a certificate related to that.

I had already installed riot on another yunohost but without having this issue (I can't find the logs anymore on that instance, don't really understand why). But I think the grep operations must not have been returning anything since there was no subdomain of `chosenMatrixDomain.tld` in that other instance.

So what I understand from that is that the error occur when grep is finding matches (domains with similar names), but in fact it shouldn't because it's not the exact domain name.
Maybe this issue can be of some help to improve the script. (But I'm still curious why looking for this `/etc/yunohost/certs/chosenMatrixDomain.tld/crt.pem` link in the first place.)

Thanks for the nice and swift package :)

**Comment by Josue-T** [comment]
Hello, this is due to a depreciated configuration of synapse. Some month ago synapse used a self signed certificate. And to be able to use SSO I need to use make a request to synapse and to be able to do this I need to validate the synapse certificate.

Anyway I'm working a new and more cleaner way to manage the SSO, so this part of code will be removed.

**Comment by eauchat** [comment]
> Anyway I'm working a new and more cleaner way to manage the SSO, so this part of code will be removed.

Nice to hear that :)

Then I guess we can close this issue whenever that will be done.

**Comment by Josue-T** [comment]
Closing as it should be fixed. Please reopen if it sill not fixed
