### ISSUE TITLE
Riot has been renamed into Element

### ISSUE THREAD

**Issue by tituspijean** [YunoHost-Apps/element_ynh#23]
FYI [Riot has been rebranded into Element](https://element.io/blog/welcome-to-element/). They seem to have handled the required redirections in their code and website, but I think we should at least acknowledge the two names in the manifest and description.

**Comment by lapineige** [comment]
How will we handle the app name change ?
Do we stick to riot, or do we change to element… which means people won't be able to upgrade automatically.

**Comment by Josue-T** [comment]
Hello,

I think as this app contains no data, the easiest solution is to rename this app and the admin will need to reinstall the new app.

I hope that there are no risk to lost the encryption key if we change the URL (or the domain). Any feedback about this ?

Le 17 juillet 2020 11:24:15 GMT+02:00, lapineige <notifications@github.com> a écrit :
>How will we handle the app name change ?>
>Do we stick to riot, or do we change to element… which means people
>won't be able to upgrade automatically.>
>>
>-- >
>You are receiving this because you are subscribed to this thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/YunoHost-Apps/riot_ynh/issues/23#issuecomment-659990318

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by lapineige** [comment]
Then we need to advertise the change properly in the forum/readme and so on, to be sure admins know what changed.

**Comment by Josue-T** [comment]
Yes, indeed

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by tituspijean** [comment]
On a side node, per [GitHub's documentation](https://docs.github.com/en/github/administering-a-repository/renaming-a-repository), if we were to rename the repository the old naming would still work. So if we forget to update some links, it will not break right away. :)

> In addition to redirecting web traffic, all git clone, git fetch, or git push operations targeting the previous location will continue to function as if made on the new location. However, to reduce confusion, we strongly recommend updating any existing local clones to point to the new repository URL.

**Comment by jershon** [comment]
What about :
1. Create a new app called element_ynh. (it will contain the same code, but in a new repository)
2. Mark this one as deprecated and give a migration guide explaining how to install the new one and remove the old one.

I think it is a good way to communicate properly about the change.

**Comment by Josue-T** [comment]
Hello,

I've pushed on a [new branch](https://github.com/YunoHost-Apps/riot_ynh/tree/element) the new app with the new name and the process, how to migrate.

Any feedback is welcome

> Create a new app called element_ynh. (it will contain the same code, but in a new repository)

I prefer to keep this repository as we can keep all issues and PR linked to this app.

**Comment by kay0u** [comment]
The commit in the list is not valid: https://github.com/YunoHost/apps/blob/489398a73fe3dbb397f5764e1212e4fc13cc2371/apps.json#L2536
