### ISSUE TITLE
Cannot log into an old account

### ISSUE THREAD

**Issue by autra** [YunoHost-Apps/element_ynh#24]
# Description

When installing synapse + riot, I created an account (it seems to have been before auth integration with yunohost).

After an update (some months ago I guess), I cannot log into this account anymore. The only possibility I have is to log with my yunohost account. 

Would it be possible to access the old account? Or migrate it to my yunohost username somehow?

Thanks!

**Comment by Josue-T** [comment]
Hello,

Maybe it's linked to what I explained here: https://github.com/YunoHost-Apps/synapse_ynh/issues/195#issuecomment-624862886

Can you confirm this ?

**Comment by Josue-T** [comment]
With the last element version it should be possible to authenticate manually without the SSO. So I consider as fixed. Please reopen if still not fixed.

**Comment by autra** [comment]
In the meantime, an upgrade broke my synapse instance, and the restoration script was *also* broken. All of these was some months ago, and I recently reinstalled fresh instances of both of them (testing branch for synapse, because master is not installable at the moment). So yes, let's keep this closed, it's not relevant to me any more, thanks.
