### ISSUE TITLE
Ability to disable signup button, and directly open sso login form

### ISSUE THREAD

**Issue by eauchat** [YunoHost-Apps/element_ynh#29]
At the moment, if I open element, I get the options: `Sign in` and `Create Account`.
If I choose `Sign in`, I can enter credentials or `Continue with CAS`, and I still have the possibility to `Create Account` displayed in small.

If at first or second step, I click `Create Account`, I get redirected to the login form, even if I was already on it.

In my server, since accounts are created from yunohost, those `Create Account` buttons are misleading for users, and also a bit cumbersome to have to click many times on sign in when this is the only thing one can do.

It seems to me that opening element, should just open directly the sso login page.
If some users want to be able to choose a custom homeserver at login, there could be a setting to enable the displaying of those forms. Or the default behaviour could be the current and a setting could allow to display sso directly.

Well that's just an idea to make things smoother, since element/matrix is already not that smooth of a concept for non-techy users ;)

*element_ynh version:* 1.8.5~ynh1

**Comment by Gredin67** [comment]
An improvement towards better UX is available in the synapse config
```
password_config:
   # Uncomment to disable password login
   #
   enabled: false
```
https://github.com/YunoHost-Apps/synapse_ynh/issues/315

**Comment by Gredin67** [comment]
If @Josue-T agrees I would close this. Even though from my point of view it would be nice if the user would have max one click to connect through the SSO...

**Comment by ericgaspar** [comment]
We can add the following in `config.json` to skip the welcome page and start with the SSO page
```
"embedded_pages": {
        "login_for_welcome": true
 }
```

**Comment by Gredin67** [comment]
@ericgaspar @eauchat I would add this option by default, definitely better with the typical Yunohost use-case.

**Comment by Josue-T** [comment]
This fix also the issue: https://github.com/YunoHost-Apps/synapse_ynh/pull/339
