### ISSUE TITLE
uprade to 1.10.15~ynh1 complete with config error

### ISSUE THREAD

**Issue by rosbeef** [YunoHost-Apps/element_ynh#59]
### Describe the bug

Uprade to 1.10.15~ynh1 complete with config error 
seems to be a cors error only on firefox

### Context

- Hardware: odroid hc1 armhf(v7)
- YunoHost version: 4.3.6.3
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: yes
  - If yes, please explain: inside lxc container
- Using, or trying to install package version/branch: master
If upgrading, current package version: 1.10.14~ynh1 

### Steps to reproduce

Update from web or cli

### Expected behavior

Config files works or update fails
if update complete and config file does not work, ability to restore last version manually does not work

### Logs
[https://paste.yunohost.org/raw/biborutape](https://paste.yunohost.org/raw/biborutape)
![image](https://user-images.githubusercontent.com/29942937/175259834-c0da0c16-de32-4264-b27c-5ac6d28c8908.png)

console output

> Content Security Policy: Ce site (https://chat.3cmr.fr) possède une politique Report-Only sans URI de rapport. CSP ne bloquera ```
> pas cette politique et ne pourra pas rapporter ses violations.
> Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à https://home.3cmr.fr/yunohost/sso/ (« font-src »). 2
> Content Security Policy: Ce site (https://chat.3cmr.fr) possède une politique Report-Only sans URI de rapport. CSP ne bloquera pas cette politique et ne pourra pas rapporter ses violations. 4
> Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à https://home.3cmr.fr/yunohost/sso/ (« font-src »). 5
> Content Security Policy: Ce site (https://chat.3cmr.fr) possède une politique Report-Only sans URI de rapport. CSP ne bloquera pas cette politique et ne pourra pas rapporter ses violations.
> Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à https://home.3cmr.fr/yunohost/sso/ (« font-src »).
> Content Security Policy: Ce site (https://chat.3cmr.fr) possède une politique Report-Only sans URI de rapport. CSP ne bloquera pas cette politique et ne pourra pas rapporter ses violations. 2
> Initialised rageshake. rageshake.ts:64:12
> To fix line numbers in Chrome: Meatball menu → Settings → Ignore list → Add /rageshake\.js$ rageshake.ts:64:12
> Using Web platform rageshake.ts:64:12
> wasm streaming compile failed: TypeError: WebAssembly: Response has unsupported MIME type 'application/octet-stream' expected 'application/wasm' rageshake.ts:64:12
> falling back to ArrayBuffer instantiation rageshake.ts:64:12
> Using WebAssembly Olm rageshake.ts:64:12
> No bug report endpoint set - logs will not be persisted rageshake.ts:64:12
> set language to fr rageshake.ts:64:12
> Application is running in production mode rageshake.ts:64:12
> Vector starting at https://chat.3cmr.fr/element/ rageshake.ts:64:12
> startUpdater, current version is 1.10.15 rageshake.ts:64:12
> Verifying homeserver configuration rageshake.ts:64:12
> Config uses a default_server_name - doing .well-known lookup rageshake.ts:64:12
> DEPRECATED CONFIG OPTION: In the future, default_server_name will not be accepted. Please use default_server_config instead. rageshake.ts:64:12
> No update available, already on 1.10.15 rageshake.ts:64:12
> No response or error when parsing .well-known rageshake.ts:64:12
>     r rageshake.ts:64
>     methodFactory logger.ts:50
>     findClientConfig autodiscovery.ts:338
> Invalid JSON rageshake.ts:64:12
> Error processing homeserver config: 
> Object { state: "FAIL_PROMPT", error: "Invalid homeserver discovery response", base_url: null }
> rageshake.ts:64:12
> Error: Invalid homeserver discovery response
>     y languageHandler.tsx:60
>     buildValidatedConfigFromDiscovery AutoDiscoveryUtils.tsx:242
>     k app.tsx:219
> rageshake.ts:64:12
> La ressource à l’adresse « https://chat.3cmr.fr/fonts/Inter/Inter-BoldItalic.2129bd0.woff2 » préchargée avec le préchargement de lien n’a pas été utilisée après quelques secondes. Assurez-vous que tous les attributs de la balise de préchargement sont définis correctement. element
> La ressource à l’adresse « https://chat.3cmr.fr/fonts/Inter/Inter-Bold.fc28dff.woff2 » préchargée avec le préchargement de lien n’a pas été utilisée après quelques secondes. Assurez-vous que tous les attributs de la balise de préchargement sont définis correctement. element
> La ressource à l’adresse « https://chat.3cmr.fr/fonts/Inter/Inter-SemiBoldItalic.10a60d8.woff2 » préchargée avec le préchargement de lien n’a pas été utilisée après quelques secondes. Assurez-vous que tous les attributs de la balise de préchargement sont définis correctement. element
> La ressource à l’adresse « https://chat.3cmr.fr/fonts/Inter/Inter-SemiBold.0802d48.woff2 » préchargée avec le préchargement de lien n’a pas été utilisée après quelques secondes. Assurez-vous que tous les attributs de la balise de préchargement sont définis correctement. element
> La ressource à l’adresse « https://chat.3cmr.fr/fonts/Inter/Inter-MediumItalic.8154ac2.woff2 » préchargée avec le préchargement de lien n’a pas été utilisée après quelques secondes. Assurez-vous que tous les attributs de la balise de préchargement sont définis correctement. element
> La ressource à l’adresse « https://chat.3cmr.fr/fonts/Inter/Inter-Medium.027d14e.woff2 » préchargée avec le préchargement de lien n’a pas été utilisée après quelques secondes. Assurez-vous que tous les attributs de la balise de préchargement sont définis correctement. element
> La ressource à l’adresse « https://chat.3cmr.fr/fonts/Inter/Inter-Italic.b791861.woff2 » préchargée avec le préchargement de lien n’a pas été utilisée après quelques secondes. Assurez-vous que tous les attributs de la balise de préchargement sont définis correctement. element
> La ressource à l’adresse « https://chat.3cmr.fr/fonts/Inter/Inter-Regular.4232a67.woff2 » préchargée avec le préchargement de lien n’a pas été utilisée après quelques secondes. Assurez-vous que tous les attributs de la balise de préchargement sont définis correctement. element
> Content Security Policy: Ce site (https://chat.3cmr.fr) possède une politique Report-Only sans URI de rapport. CSP ne bloquera pas cette politique et ne pourra pas rapporter ses violations. 2
> No update available, already on 1.10.15 rageshake.ts:64:12
>

**Comment by rosbeef** [comment]
add 
```

	location /.wellknown/matrix/client {
	    	add_header 'Access-Control-Allow-Origin' '*';
	}
```

to nginx synaps.conf file should work

**Comment by ericgaspar** [comment]
should be fixed with #62
